ALTER TABLE users
    ADD client_id BIGINT;

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_CLIENT FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE;

ALTER TABLE users
DROP
CONSTRAINT fk_users_on_admin_info;

ALTER TABLE users
DROP
COLUMN admin_info_id;