ALTER TABLE product_owner_products
DROP
CONSTRAINT fk4v5de1oewl4hn13m1oo3fo99e;

ALTER TABLE product_owner_products
DROP
CONSTRAINT fkn69gv2r0fybxvqpy7gp71j72v;

DROP TABLE product_owner_products CASCADE;