spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Cargotrucking
    username: postgres
    password: 1111
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  flyway:
    user: postgres
    password: 1111
    schemas: Cargotrucking
    enabled: true