spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cargotrucking
    username: postgres
    password: 1111
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
#  flyway:
#    enabled: true
#    baseline-on-migrate: true
logging:
  level:
    org.hibernate.sql: debug
jwt:
  secret: Thequickbrownfoxjumpsoverthelazydog
  expiration: 172800000