spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cargotrucking
    username: postgres
    password: 1111
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    generate-ddl: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
logging:
  level:
    org.hibernate.sql: debug
jwt:
  secret: Thequickbrownfoxjumpsoverthelazydog
  expiration:
    refresh: 172800000
    access: 180000
mail:
  login: sasha.pinsk03@gmail.com
  password: ndqvwiahjiezaabm
  host: smtp.gmail.com
  port: 587