spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cargotrucking
    username: postgres
    password: 1111
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
logging:
  level:
    org.hibernate.sql: debug
jwt:
  secret: Thequickbrownfoxjumpsoverthelazydog
  expiration:
    refresh: 172800000
    access: 1800000